name: Check EOL

on: push

jobs:
  my-workflow:
    name: Example workflow using the Check EOL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v1

      - name: Use this action to check EOL
        uses: AODocs/check-eol@main